---
title: "Conferences"
---

## Meetings Attended
CRUK City of London Centre Datathon 2025 – London, UK (Jan 2025)  
BSI Congress 2023 – Belfast, Northern Ireland, UK (Dec 2023)  

## Presentation
8th UK & Germany Lymphoma Retreat – Peak District, UK (Oct 2024)  
Title: Aberrant MYC Overexpression Drives Germinal Centre B Cell In Lymphomagenesis

## Poster Contribution
66th ASH Annual Meeting and Exposition – San Diego, California, US (Dec 2024)  
Title: Characterising and Targeting Follicular Lymphoma's Common Progenitor Cells  
Oral presentation by Dr Dinis Calado

EMBO Workshop: Lymphoid Tissues and Germinal Centres in Immune Reactions – Galway, Ireland, UK (Jul 2024)  
Title: Timestamping of plasma cells reveals diverse gene signatures determining longevity potential  
Poster presentation by Dr Anqi Xu  

West German Lymphoma Symposium: Clinic meets Biology – Essen, Germany (May 2024)
Title: Unveiling Follicular Lymphoma's Common Progenitor Cells  
Poster presentation by Dr Oscar Atkins  
Awarded 3rd Place  

BSI Congress 2023 – Belfast, Northern Ireland, UK (Dec 2023)  
Title: MYC overexpression promotes germinal centre B cell independency from T cell help  
Oral & poster presentation by Baizhi Chen, PhD student  
