---
title: "Education"
---

## MRes Translational Cancer Medicine
Grade: Distinction
King’s College London, UK  
Sep 2021 – Oct 2022  
  

Thesis 1  
Single-cell RNA sequencing revealed distinct molecular interactions involving Treg & Tfh between metastatic & cancer-free lymph nodes from breast cancer patients (72%)  
Thesis 2  
The role of IL-1β, IFN-γ and hypoxia in Treg modulation and its implications in the pathogenesis of aplastic anaemia (85%)  
Coursework  
The significance of translational research on immune checkpoint inhibitors for combination chemotherapy in triple negative breast cancer patients (71%)  
  
## BSc Medical Biosciences  
Grade: First-Class  
Imperial College London, UK  
Sep 2018 – Jul 2021  
  
Modules  
Cancer Biology (73%), Immunology & Inflammation (68%), Genetics & Genomics (64%), Molecular Cellular Biology (74%), Statistics (67%), Microbiome in Health & Diseases (76%)  
Thesis  
Silencing of KLF2 augments endothelial dysfunction associated with pulmonary arterial hypertension (73%)  
  
## GCE A-Levels  
Grade: A\*A\*AAA  
Abingdon School, Oxfordshire, UK  
Sep 2016 – Jul 2018  
  
Subjects  
Maths (A*), EPQ (A*), Further Maths (A), Biology (A), Chemistry (A)  
